[target.thumbv6m-none-eabi]
runner = "probe-rs run --chip STM32L072CBTx"

[build]
target = "thumbv6m-none-eabi"

[target.'cfg(all(target_arch = "arm", target_os = "none"))']
rustflags = [
  "-C", "link-arg=-Tlink.x",
  "-C", "link-arg=-Tdefmt.x",
]

[env]
DEFMT_LOG = "info"

[alias]
run-receiver = "run --release --features receiver"
run-transmitter = "run --release --features transmitter"