// /src/sim800.rs
use defmt::{error, info, warn};
use embassy_time::{Duration, Timer, with_timeout};
use heapless::String;

use crate::constants::*;
use crate::custom_strings::separate_chars_by_commas;
use crate::gsm_time_converter::GsmTime;
use crate::hardware::{ModemControl, ModemControlInterface, ModemRx, ModemTx, PowerState};
use crate::phone_book::PhoneBook;
use crate::runtime::{USB_RX_PIPE, USB_TX_PIPE};
use crate::sim800_logic::{
    AlarmCallDecision, AlarmDedupState, UsbCommandState, decide_alarm_call, first_phonebook_number,
};
use crate::sim800_parser::{
    ParsedUrc, classify_urc, line_indicates_call_connected, line_indicates_call_failed,
    parse_clts_query_line, parse_cpbr_number, parse_dtmf_char,
};
use embassy_sync::blocking_mutex::raw::CriticalSectionRawMutex;
use embassy_sync::channel::{Receiver, Sender};

const HANDSHAKE_TIMEOUT_MS: u64 = 1000;
const DEFAULT_TIMEOUT_MS: u64 = 1000;
const HANDSHAKE_ATTEMPTS: usize = 6;
const DMA_CHUNK_SIZE: usize = 256; // DMA Chunk buffer to prevent overrun errors
const NETWORK_REGISTRATION_TIMEOUT_SECONDS: usize = 30;
const PHONEBOOK_CAPACITY: usize = 8;

#[derive(Clone, defmt::Format, PartialEq, Debug)]
pub enum SimError {
    Timeout,
    SerialError,
    AtError,
    CallFailed,
}

// Types for communication
#[derive(Clone, defmt::Format, PartialEq, Debug)]
pub enum Command {
    Init,
    UsbConnected,
    UsbDisconnected,
    SendMessage {
        phone_number: String<MAX_PHONE_LENGTH>,
        message: String<SIM800_LINE_BUFFER_SIZE>,
    },
    SendAlarmSms {
        message: String<SIM800_LINE_BUFFER_SIZE>,
    },
    CallWithDtmf {
        phone_number: String<MAX_PHONE_LENGTH>,
        dtmf: String<DTMF_PACKET_LENGTH>,
    },
    CallAlarmWithDtmf {
        dtmf: String<DTMF_PACKET_LENGTH>,
    },
    HandleIncomingCall {
        phone_number: String<MAX_PHONE_LENGTH>,
    },
    UpdateTime,
}

// Events generated by SIM800 (URCs)
#[derive(Clone, defmt::Format)]
pub enum SimEvent {
    SmsReceived {
        number: String<MAX_PHONE_LENGTH>,
        message: String<SIM800_LINE_BUFFER_SIZE>,
    },
    CallReceived {
        number: String<MAX_PHONE_LENGTH>,
    },
    DtmfReceived(char),
    CallEnded,
    CallExecuted(bool),
    TimeReceived(GsmTime),
}

pub struct Sim800Driver<C = ModemControl> {
    tx: ModemTx,
    rx: ModemRx,
    control: C,
    phone_book: PhoneBook,
    line_buf:[u8; SIM800_LINE_BUFFER_SIZE],
    line_pos: usize,
    rx_buf:[u8; DMA_CHUNK_SIZE], // DMA Chunk buffer to prevent overrun errors
    rx_buf_pos: usize,
    rx_buf_len: usize,
    alarm_dedup: AlarmDedupState,
    usb_cmd: UsbCommandState,
    usb_connected: bool,
    is_powered: bool,
    event_channel: Option<Sender<'static, CriticalSectionRawMutex, SimEvent, 4>>,
}

impl<C: ModemControlInterface> Sim800Driver<C> {
    pub fn new(tx: ModemTx, rx: ModemRx, control: C) -> Self {
        Self {
            tx,
            rx,
            control,
            phone_book: PhoneBook::new(),
            line_buf:[0u8; SIM800_LINE_BUFFER_SIZE],
            line_pos: 0,
            rx_buf:[0u8; DMA_CHUNK_SIZE],
            rx_buf_pos: 0,
            rx_buf_len: 0,
            alarm_dedup: AlarmDedupState::new(),
            usb_cmd: UsbCommandState::new(),
            usb_connected: false,
            is_powered: false,
            event_channel: None,
        }
    }

    /// Fetches bytes using chunked DMA reading to eliminate Overrun Drops
    async fn read_byte(&mut self) -> Result<u8, SimError> {
        loop {
            if self.rx_buf_pos < self.rx_buf_len {
                let b = self.rx_buf[self.rx_buf_pos];
                self.rx_buf_pos += 1;
                return Ok(b);
            }
            
            match self.rx.read_until_idle(&mut self.rx_buf).await {
                Ok(0) => {
                    let mut b =[0u8; 1];
                    self.rx.read(&mut b).await.map_err(|_| SimError::SerialError)?;
                    self.rx_buf[0] = b[0];
                    self.rx_buf_len = 1;
                    self.rx_buf_pos = 0;
                }
                Ok(n) => {
                    self.rx_buf_len = n;
                    self.rx_buf_pos = 0;
                }
                Err(_) => return Err(SimError::SerialError),
            }
        }
    }

    async fn read_line(&mut self) -> Result<String<SIM800_LINE_BUFFER_SIZE>, SimError> {
        loop {
            let b = self.read_byte().await?;

            if b == b'\n' {
                let mut len = self.line_pos;
                if len > 0 && self.line_buf[len - 1] == b'\r' {
                    len -= 1;
                }
                
                let mut s = String::<SIM800_LINE_BUFFER_SIZE>::new();
                if let Ok(valid_str) = core::str::from_utf8(&self.line_buf[..len]) {
                    let _ = s.push_str(valid_str);
                    
                    if !s.trim().is_empty() {
                        let mut debug_out = String::<SIM800_LINE_BUFFER_SIZE>::new();
                        let _ = core::fmt::write(&mut debug_out, format_args!("\r\n[SIM] {}", valid_str));
                        let mut offset = 0;
                        let bytes = debug_out.as_bytes();
                        while offset < bytes.len() {
                            let space = core::cmp::min(bytes.len() - offset, 64);
                            let _ = USB_TX_PIPE.try_write(&bytes[offset..offset + space]);
                            offset += space;
                        }
                    }
                }
                
                self.line_pos = 0;
                return Ok(s);
            } else if b != b'\r' {
                if self.line_pos < self.line_buf.len() {
                    self.line_buf[self.line_pos] = b;
                    self.line_pos += 1;
                }
            }
        }
    }

    async fn read_line_and_process_urcs(&mut self) -> Result<String<SIM800_LINE_BUFFER_SIZE>, SimError> {
        let s = self.read_line().await?;
        if let Some(urc) = classify_urc(&s) {
            self.process_urc(urc).await;
        }
        Ok(s)
    }

    async fn process_urc(&mut self, urc: ParsedUrc) {
        let Some(channel) = self.event_channel.clone() else { return; };
        match urc {
            ParsedUrc::SmsHeader { number } => {
                if let Ok(msg) = self.read_line().await {
                    channel.send(SimEvent::SmsReceived { number, message: msg }).await;
                }
            }
            ParsedUrc::Clip { number } => channel.send(SimEvent::CallReceived { number }).await,
            ParsedUrc::Dtmf(c) => channel.send(SimEvent::DtmfReceived(c)).await,
            ParsedUrc::Time(time) => {
                info!("Time received (URC): {}-{}-{} {}:{}:{}", time.year, time.month, time.day, time.hour, time.minute, time.second);
                channel.send(SimEvent::TimeReceived(time)).await;
            }
        }
    }

    async fn send_str(&mut self, s: &str) {
        if s.is_empty() { return; }

        let clean_str = s.trim_end();
        if !clean_str.is_empty() {
            let mut debug_out = String::<SIM800_LINE_BUFFER_SIZE>::new();
            let _ = core::fmt::write(&mut debug_out, format_args!("\r\n[MCU] {}", clean_str));
            
            let mut offset = 0;
            let bytes = debug_out.as_bytes();
            while offset < bytes.len() {
                let space = core::cmp::min(bytes.len() - offset, 64);
                let _ = USB_TX_PIPE.try_write(&bytes[offset..offset + space]);
                offset += space;
            }
        }

        let _ = self.tx.write(s.as_bytes()).await;
    }

    async fn send_cmd_wait_ok(&mut self, cmd: &str, timeout_ms: u64) -> Result<(), SimError> {
        self.send_str(cmd).await;
        self.send_str("\r\n").await;

        let res = with_timeout(Duration::from_millis(timeout_ms), async {
            loop {
                let mut cpbr_data: Option<String<MAX_PHONE_LENGTH>> = None;

                {
                    let line = self.read_line_and_process_urcs().await?;
                    
                    // Robust check: Tolerates dropped first characters from Overrun errors
                    if line.contains("OK") { return Ok::<(), SimError>(()); }
                    if line.contains("ERROR") || line.contains("RROR") { return Err(SimError::AtError); }

                    if let Some(num) = parse_cpbr_number(&line) { cpbr_data = Some(num); }
                }
                if let Some(num) = cpbr_data { let _ = self.phone_book.add_number(&num); }
            }
        }).await;

        match res {
            Ok(Ok(())) => Ok(()),
            Ok(Err(e)) => Err(e),
            Err(_) => Err(SimError::Timeout),
        }
    }

    pub async fn power_on(&mut self) {
        if self.is_powered { return; }
        info!("Starting SIM800 Power Sequence...");

        self.control.set_dc_power(PowerState::On);
        Timer::after(Duration::from_millis(1500)).await;

        // Flush any garbage bytes from power up
        self.rx_buf_len = 0; 
        self.rx_buf_pos = 0;
        self.line_pos = 0;

        // Test if already awake (prevents lockups on quick restarts)
        self.send_str("AT\r\n").await;
        let awake = with_timeout(Duration::from_millis(800), self.read_line_and_process_urcs()).await.is_ok();

        if !awake {
            info!("Pulsing PWRKEY...");
            self.control.set_power_key(PowerState::On);
            Timer::after(Duration::from_millis(1200)).await;
            self.control.set_power_key(PowerState::Off);
            info!("Waiting for SIM800 boot...");
            Timer::after(Duration::from_secs(INIT_SIM800_DELAY_SECONDS as u64)).await;
        } else {
            info!("SIM800 was already awake.");
        }

        // Spam ATE0 to shut off echo immediately and prevent UART Overruns!
        for _ in 0..HANDSHAKE_ATTEMPTS {
            self.send_str("ATE0\r\n").await;
            Timer::after(Duration::from_millis(200)).await;
            if self.send_cmd_wait_ok("AT", HANDSHAKE_TIMEOUT_MS).await.is_ok() {
                break;
            }
        }
        self.send_cmd_wait_ok("ATE0", DEFAULT_TIMEOUT_MS).await.ok(); 

        info!("Waiting for Network Registration...");
        for _ in 0..NETWORK_REGISTRATION_TIMEOUT_SECONDS {
            self.send_str("AT+CREG?\r\n").await;
            let mut registered = false;
            let _ = with_timeout(Duration::from_millis(DEFAULT_TIMEOUT_MS), async {
                loop {
                    let line = self.read_line_and_process_urcs().await?;
                    if line.contains("+CREG: 0,1") || line.contains("+CREG: 0,5") || line.contains("+CREG: 1,1") || line.contains("+CREG: 1,5") {
                        registered = true;
                    }
                    if line.contains("OK") || line.contains("ERROR") || line.contains("RROR") {
                        break Ok::<(), SimError>(());
                    }
                }
            }).await;
            
            if registered {
                info!("Network registered!");
                break;
            }
            Timer::after(Duration::from_secs(1)).await;
        }

        // Extra delay to let SMS Engine and Phonebook finish initializing
        Timer::after(Duration::from_secs(2)).await;

        let cmds =[
            "AT+CMEE=1",          
            "AT+CLIP=1",          
            "AT+CMGF=1",          
            "AT+CSCS=\"GSM\"",    
            "AT+CNMI=1,2,0,1,0",  
            "AT+CSMP=49,167,0,0", 
            "AT+CREG=1",          
            "AT+DDET=1",          
        ];

        for cmd in cmds {
            let mut attempts = 0;
            loop {
                if self.send_cmd_wait_ok(cmd, DEFAULT_TIMEOUT_MS).await.is_ok() { break; }
                attempts += 1;
                if attempts > 3 {
                    error!("CMD failed: {}", cmd);
                    break;
                }
                Timer::after(Duration::from_millis(500)).await;
            }
        }

        info!("Loading Phonebook...");
        for i in 1..=PHONEBOOK_CAPACITY {
            let mut buf = String::<16>::new();
            use core::fmt::Write;
            let _ = write!(buf, "AT+CPBR={}", i);
            if let Err(e) = self.send_cmd_wait_ok(&buf, DEFAULT_TIMEOUT_MS).await {
                warn!("Failed to load phonebook index {}: {:?}", i, e);
            }
        }

        // Apply CLTS at the very end to avoid messing up the earlier init process
        match self.check_clts_enabled().await {
            Ok(false) => {
                info!("CLTS disabled. Enabling and Rebooting...");
                let _ = self.send_cmd_wait_ok("AT+CLTS=1", DEFAULT_TIMEOUT_MS).await;
                let _ = self.send_cmd_wait_ok("AT&W", DEFAULT_TIMEOUT_MS).await; 
                self.send_str("AT+CFUN=1,1\r\n").await;
                Timer::after(Duration::from_secs(8)).await;
                let _ = self.send_cmd_wait_ok("AT", DEFAULT_TIMEOUT_MS).await;
                let _ = self.send_cmd_wait_ok("ATE0", DEFAULT_TIMEOUT_MS).await;
            }
            Ok(true) => info!("CLTS is already enabled."),
            Err(e) => warn!("Failed to query CLTS status: {:?}", e),
        }

        self.is_powered = true;
        info!("SIM800 Initialized and Ready");
    }

    pub async fn power_off(&mut self) {
        if !self.is_powered { return; }
        info!("Disabling SIM800 power supply...");
        self.control.set_power_key(PowerState::Off);
        Timer::after(Duration::from_millis(100)).await;
        self.control.set_dc_power(PowerState::Off);
        
        // Give capacitors ample time to drain so module fully shuts down
        Timer::after(Duration::from_millis(2500)).await;
        self.is_powered = false;
    }

    async fn check_clts_enabled(&mut self) -> Result<bool, SimError> {
        self.send_str("AT+CLTS?\r\n").await;
        let mut is_enabled = None;
        let res = with_timeout(Duration::from_millis(2000), async {
            loop {
                let line = self.read_line_and_process_urcs().await?;
                if line.contains("OK") { return Ok::<(), SimError>(()); }
                if line.contains("ERROR") || line.contains("RROR") { return Err(SimError::AtError); }
                if let Some(enabled) = parse_clts_query_line(&line) { is_enabled = Some(enabled); }
            }
        }).await;

        match res {
            Ok(Ok(())) => is_enabled.ok_or(SimError::AtError),
            Ok(Err(e)) => Err(e),
            Err(_) => Err(SimError::Timeout),
        }
    }

    async fn execute_update_time(&mut self) {
        self.ensure_powered().await;
        if let Err(e) = self.send_cmd_wait_ok("AT+CCLK?", 2000).await {
            warn!("Failed to query time from SIM800: {:?}", e);
        }
    }

    async fn ensure_powered(&mut self) {
        if !self.is_powered { self.power_on().await; }
    }

    async fn restore_usb_modem_mode_if_needed(&mut self) {
        #[cfg(feature = "receiver")] { self.power_on().await; }
        #[cfg(not(feature = "receiver"))] {
            if self.usb_connected { self.power_on().await; } 
            else { self.power_off().await; }
        }
    }

    pub async fn send_sms(&mut self, number: &str, message: &str) -> Result<(), SimError> {
        self.ensure_powered().await;
        
        let mut cmd = String::<SIM800_SMS_SIZE>::new();
        use core::fmt::Write;
        let _ = write!(cmd, "AT+CMGS=\"{}\"", number);
        self.send_str(&cmd).await;
        self.send_str("\r\n").await;

        let res = with_timeout(Duration::from_secs(5), async {
            self.line_pos = 0;
            loop {
                let b = self.read_byte().await?;

                if b == b'>' {
                    self.line_pos = 0;
                    return Ok::<(), SimError>(());
                } else if b == b'\n' {
                    let mut len = self.line_pos;
                    if len > 0 && self.line_buf[len - 1] == b'\r' { len -= 1; }
                    
                    let parsed_urc = if let Ok(s) = core::str::from_utf8(&self.line_buf[..len]) {
                        classify_urc(s)
                    } else { None };

                    if let Some(urc) = parsed_urc { self.process_urc(urc).await; }
                    self.line_pos = 0;
                } else if b != b'\r' {
                    if self.line_pos < self.line_buf.len() {
                        self.line_buf[self.line_pos] = b;
                        self.line_pos += 1;
                    }
                }
            }
        }).await;

        match res {
            Ok(Ok(())) => {},
            Ok(Err(e)) => return Err(e),
            Err(_) => return Err(SimError::Timeout),
        }

        self.send_str(message).await;
        let ctrl_z =[0x1Au8];
        let _ = self.tx.write(&ctrl_z).await;

        self.send_cmd_wait_ok("", 10000).await
    }

    pub async fn make_call_dtmf(&mut self, number: &str, dtmf: &str) -> Result<(), SimError> {
        self.ensure_powered().await;
        
        let mut cmd = String::<64>::new();
        use core::fmt::Write;
        let _ = write!(cmd, "ATD{};", number);
        self.send_str(&cmd).await;
        self.send_str("\r\n").await;

        let result = with_timeout(Duration::from_secs(20), async {
            loop {
                let line = self.read_line_and_process_urcs().await?;
                info!("Call setup line: {}", line.as_str());
                if line_indicates_call_connected(&line, ONLINE_SIGNAL.chars().next().unwrap_or('\0')) {
                    return Ok::<(), SimError>(());
                }
                if line_indicates_call_failed(&line) { return Err(SimError::CallFailed); }
            }
        }).await;

        match result {
            Ok(Ok(())) => {}
            Ok(Err(e)) => {
                self.send_cmd_wait_ok("AT+CHUP", DEFAULT_TIMEOUT_MS).await.ok();
                return Err(e);
            }
            Err(_) => {
                self.send_cmd_wait_ok("AT+CHUP", DEFAULT_TIMEOUT_MS).await.ok();
                return Err(SimError::Timeout);
            }
        }

        let mut out_buf =[0u8; 64];
        if let Some(csv) = separate_chars_by_commas(dtmf, &mut out_buf) {
            let mut cmd = String::<64>::new();
            use core::fmt::Write;
            let _ = write!(cmd, "AT+VTS=\"{}\"", csv);
            self.send_cmd_wait_ok(&cmd, 5000).await?;
        } else {
            self.send_cmd_wait_ok("AT+CHUP", DEFAULT_TIMEOUT_MS).await.ok();
            return Err(SimError::AtError);
        }

        let confirm_res = with_timeout(Duration::from_secs(10), async {
            loop {
                let line = self.read_line_and_process_urcs().await?;
                info!("Received during confirmation wait: {}", line.as_str());
                if line_indicates_call_failed(&line) { return Err(SimError::CallFailed); }
                if line_indicates_call_connected(&line, CONFIRMATION_SIGNAL.chars().next().unwrap_or('\0')) {
                    self.send_cmd_wait_ok("AT+CHUP", DEFAULT_TIMEOUT_MS).await.ok();
                    return Ok::<(), SimError>(());
                }
            }
        }).await;

        match confirm_res {
            Ok(Ok(())) => Ok(()),
            Ok(Err(e)) => {
                self.send_cmd_wait_ok("AT+CHUP", DEFAULT_TIMEOUT_MS).await.ok();
                Err(e)
            }
            Err(_) => {
                self.send_cmd_wait_ok("AT+CHUP", DEFAULT_TIMEOUT_MS).await.ok();
                Err(SimError::Timeout)
            }
        }
    }

    pub async fn handle_incoming_call_flow(&mut self) {
        self.ensure_powered().await;
        self.send_cmd_wait_ok("ATA", 2000).await.ok();
        Timer::after(Duration::from_secs(1)).await;

        let mut cmd = String::<32>::new();
        use core::fmt::Write;
        let _ = write!(cmd, "AT+VTS=\"{}\"", ONLINE_SIGNAL);
        self.send_cmd_wait_ok(&cmd, 2000).await.ok();

        let mut dtmf_buf = String::<DTMF_PACKET_LENGTH>::new();

        let receive_res = with_timeout(Duration::from_secs(10), async {
            loop {
                let line = self.read_line_and_process_urcs().await?;
                info!("Incoming call flow line: {}", line.as_str());
                if let Some(c) = parse_dtmf_char(&line) { dtmf_buf.push(c).ok(); }
                if dtmf_buf.len() >= DTMF_PACKET_LENGTH { return Ok::<(), SimError>(()); }
                if line.contains("NO CARRIER") { return Err(SimError::CallFailed); }
            }
        }).await;

        if matches!(receive_res, Ok(Ok(()))) {
            cmd.clear();
            let _ = write!(cmd, "AT+VTS=\"{}\"", CONFIRMATION_SIGNAL);
            self.send_cmd_wait_ok(&cmd, 2000).await.ok();
            Timer::after(Duration::from_secs(1)).await;
        }

        if let Some(channel) = &self.event_channel { channel.send(SimEvent::CallEnded).await; }
    }

    pub async fn run(
        &mut self,
        cmd_channel: Receiver<'static, CriticalSectionRawMutex, Command, 4>,
        event_channel: Sender<'static, CriticalSectionRawMutex, SimEvent, 4>,
    ) {
        self.event_channel = Some(event_channel.clone());
        let mut uptime_sec: u64 = 0;

        loop {
            use embassy_futures::select::{Either3, select3};

            let mut usb_rx_buf =[0u8; 64];
            let usb_fut = USB_RX_PIPE.read(&mut usb_rx_buf);
            
            let selection = if self.is_powered {
                select3(self.read_line_and_process_urcs(), cmd_channel.receive(), usb_fut).await
            } else {
                select3(core::future::pending(), cmd_channel.receive(), usb_fut).await
            };

            uptime_sec += 1;

            match selection {
                Either3::First(_) => {
                    // Suppressed printing here because `read_line` already outputs to USB. 
                }
                Either3::Second(cmd) => {
                    info!("Processing command: {:?}", cmd);
                    match cmd {
                        Command::Init => self.power_on().await,
                        Command::UsbConnected => {
                            self.usb_connected = true;
                            self.power_on().await;
                        }
                        Command::UsbDisconnected => {
                            self.usb_connected = false;
                            self.usb_cmd.reset();

                            #[cfg(feature = "receiver")]
                            self.power_on().await;

                            #[cfg(not(feature = "receiver"))]
                            self.power_off().await;
                        }
                        Command::SendMessage { phone_number, message } => {
                            match self.send_sms(&phone_number, &message).await {
                                Ok(_) => info!("SMS sent successfully to {}", phone_number.as_str()),
                                Err(e) => error!("Failed to send SMS to {}: {:?}", phone_number.as_str(), e),
                            }
                            self.restore_usb_modem_mode_if_needed().await;
                        }
                        Command::SendAlarmSms { message } => {
                            if let Some(target_num) = first_phonebook_number(&self.phone_book) {
                                match self.send_sms(&target_num, &message).await {
                                    Ok(_) => info!("Alarm SMS sent successfully to {}", target_num.as_str()),
                                    Err(e) => error!("Failed to send Alarm SMS to {}: {:?}", target_num.as_str(), e),
                                }
                            } else {
                                warn!("Cannot send Alarm SMS: No phonebook number available");
                            }
                            self.restore_usb_modem_mode_if_needed().await;
                        }
                        Command::CallAlarmWithDtmf { dtmf } => {
                            match decide_alarm_call(&self.phone_book, &self.alarm_dedup, &dtmf, uptime_sec) {
                                AlarmCallDecision::SkipDuplicate => {
                                    warn!("Skipping duplicate alarm call for DTMF {} (Last: {}s ago)", dtmf, uptime_sec - self.alarm_dedup.last_time);
                                    if let Some(channel) = &self.event_channel { channel.send(SimEvent::CallExecuted(true)).await; }
                                    self.restore_usb_modem_mode_if_needed().await;
                                }
                                AlarmCallDecision::PlaceCall { number } => {
                                    info!("Calling Alarm: {} with DTMF: {}", number.as_str(), dtmf.as_str());
                                    match self.make_call_dtmf(&number, &dtmf).await {
                                        Ok(_) => {
                                            info!("Alarm confirmed (#).");
                                            self.alarm_dedup.record_success(&dtmf, uptime_sec);
                                            if let Some(channel) = &self.event_channel { channel.send(SimEvent::CallExecuted(true)).await; }
                                        }
                                        Err(e) => {
                                            error!("Alarm call failed/unconfirmed: {:?}", e);
                                            if let Some(channel) = &self.event_channel { channel.send(SimEvent::CallExecuted(false)).await; }
                                        }
                                    }
                                    self.restore_usb_modem_mode_if_needed().await;
                                }
                                AlarmCallDecision::NoNumber => {
                                    warn!("No phone number for alarm call!");
                                    if let Some(channel) = &self.event_channel { channel.send(SimEvent::CallExecuted(false)).await; }
                                }
                            }
                        }
                        Command::CallWithDtmf { phone_number, dtmf } => {
                            match self.make_call_dtmf(&phone_number, &dtmf).await {
                                Ok(_) => info!("Call with DTMF succeeded."),
                                Err(e) => error!("Call with DTMF failed: {:?}", e),
                            }
                            self.restore_usb_modem_mode_if_needed().await;
                        }
                        Command::HandleIncomingCall { .. } => {
                            self.handle_incoming_call_flow().await;
                            self.restore_usb_modem_mode_if_needed().await;
                        }
                        Command::UpdateTime => {
                            self.execute_update_time().await;
                            self.restore_usb_modem_mode_if_needed().await;
                        }
                    }
                }
                Either3::Third(n) => {
                    if n > 0 {
                        for i in 0..n {
                            let b = usb_rx_buf[i];
                            let outcome = self.usb_cmd.push_byte(b, self.is_powered);

                            if outcome.echo { let _ = USB_TX_PIPE.try_write(&[b]); }
                            if outcome.forward_to_modem { let _ = self.tx.write(&[b]).await; }
                            if let Some(cmd) = outcome.command_to_execute { self.execute_mcu_command(cmd.as_str()).await; }
                        }
                    }
                }
            }
        }
    }

    async fn execute_mcu_command(&mut self, cmd: &str) {
        #[cfg(test)] { crate::runtime::execute_mcu_command(cmd).await; }
        #[cfg(not(test))] { crate::runtime::execute_mcu_command(cmd).await; }
    }
}