// /src/sim800.rs
use defmt::{error, info, warn};
use embassy_time::{Duration, Timer, with_timeout};
use heapless::String;

use crate::constants::*;
use crate::custom_strings::separate_chars_by_commas;
use crate::gsm_time_converter::GsmTime;
use crate::hardware::{ModemControl, ModemControlInterface, ModemRx, ModemTx, PowerState};
use crate::phone_book::PhoneBook;
use crate::sim800_logic::{
    AlarmCallDecision, AlarmDedupState, UsbCommandState, decide_alarm_call, first_phonebook_number,
};
use crate::sim800_parser::{
    ParsedUrc, classify_urc, line_indicates_call_connected, line_indicates_call_failed,
    parse_clts_query_line, parse_cpbr_number, parse_cclk_line, parse_dtmf_char,
};

use embassy_sync::blocking_mutex::raw::CriticalSectionRawMutex;
use embassy_sync::channel::{Receiver, Sender};
use embassy_sync::pipe::Pipe;

pub static USB_RX_PIPE: Pipe<CriticalSectionRawMutex, 256> = Pipe::new();
pub static USB_TX_PIPE: Pipe<CriticalSectionRawMutex, 1024> = Pipe::new();

const HANDSHAKE_TIMEOUT_MS: u64 = 2000;
const DEFAULT_TIMEOUT_MS: u64 = 1000;
const HANDSHAKE_ATTEMPTS: usize = 5;

// Types for communication
#[derive(Clone, defmt::Format, PartialEq, Debug)]
pub enum Command {
    Init,
    UsbConnected,
    UsbDisconnected,
    SendMessage {
        phone_number: String<MAX_PHONE_LENGTH>,
        message: String<SIM800_LINE_BUFFER_SIZE>,
    },
    SendAlarmSms {
        message: String<SIM800_LINE_BUFFER_SIZE>,
    },
    CallWithDtmf {
        phone_number: String<MAX_PHONE_LENGTH>,
        dtmf: String<DTMF_PACKET_LENGTH>,
    },
    CallAlarmWithDtmf {
        dtmf: String<DTMF_PACKET_LENGTH>,
    },
    HandleIncomingCall {
        phone_number: String<MAX_PHONE_LENGTH>,
    },
    UpdateTime,
}

// Events generated by SIM800 (URCs)
#[derive(Clone, defmt::Format)]
pub enum SimEvent {
    SmsReceived {
        number: String<MAX_PHONE_LENGTH>,
        message: String<SIM800_LINE_BUFFER_SIZE>,
    },
    CallReceived {
        number: String<MAX_PHONE_LENGTH>,
    },
    DtmfReceived(char),
    CallEnded,
    CallExecuted(bool),
    TimeReceived(GsmTime),
}

pub struct Sim800Driver<C = ModemControl> {
    tx: ModemTx,
    rx: ModemRx,
    control: C,
    phone_book: PhoneBook,
    line_buf: [u8; 128],
    alarm_dedup: AlarmDedupState,
    usb_cmd: UsbCommandState,
    usb_connected: bool,
    is_powered: bool,
}

impl<C: ModemControlInterface> Sim800Driver<C> {
    pub fn new(tx: ModemTx, rx: ModemRx, control: C) -> Self {
        Self {
            tx,
            rx,
            control,
            phone_book: PhoneBook::new(),
            line_buf: [0u8; 128],
            alarm_dedup: AlarmDedupState::new(),
            usb_cmd: UsbCommandState::new(),
            usb_connected: false,
            is_powered: false,
        }
    }

    async fn read_line(&mut self) -> Result<&str, ()> {
        let mut pos = 0;
        loop {
            let mut buf = [0u8; 1];
            match self.rx.read(&mut buf).await {
                Ok(_) => {
                    let _ = USB_TX_PIPE.try_write(&buf);
                    let b = buf[0];
                    if b == b'\n' {
                        if pos > 0 && self.line_buf[pos - 1] == b'\r' {
                            pos -= 1;
                        }
                        if let Ok(s) = core::str::from_utf8(&self.line_buf[..pos]) {
                            return Ok(s);
                        } else {
                            return Err(());
                        }
                    } else if b != b'\r' {
                        if pos < self.line_buf.len() {
                            self.line_buf[pos] = b;
                            pos += 1;
                        }
                    }
                }
                Err(_) => return Err(()),
            }
        }
    }

    async fn send_str(&mut self, s: &str) {
        if s.is_empty() {
            return;
        }

        // Write the string to our USB pipe unblockingly so it can be monitored
        let mut offset = 0;
        let bytes = s.as_bytes();
        while offset < bytes.len() {
            let space = core::cmp::min(bytes.len() - offset, 64);
            let _ = USB_TX_PIPE.try_write(&bytes[offset..offset + space]);
            offset += space;
        }

        let _ = self.tx.write(bytes).await;
    }

    async fn send_cmd_wait_ok(&mut self, cmd: &str, timeout_ms: u64) -> Result<(), ()> {
        self.send_str(cmd).await;
        self.send_str("\r\n").await;

        with_timeout(Duration::from_millis(timeout_ms), async {
            loop {
                let mut cpbr_data: Option<String<MAX_PHONE_LENGTH>> = None;

                {
                    let line = self.read_line().await?;
                    if line.trim() == "OK" {
                        return Ok(());
                    }
                    if line.trim() == "ERROR" {
                        return Err(());
                    }

                    if let Some(num) = parse_cpbr_number(line) {
                        cpbr_data = Some(num);
                    }
                }

                if let Some(num) = cpbr_data {
                    let _ = self.phone_book.add_number(&num);
                }
            }
        })
        .await
        .map_err(|_| ())?
    }

    // Specialized handler for UpdateTime to ensure +CCLK is parsed
    async fn execute_update_time(&mut self) -> Option<GsmTime> {
        self.ensure_powered().await;
        self.send_str("AT+CCLK?").await;
        self.send_str("\r\n").await;

        let mut found_time = None;

        let res = with_timeout(Duration::from_secs(2), async {
            loop {
                let line = self.read_line().await.map_err(|_| ())?;
                if line.trim() == "OK" {
                    return Ok(());
                }
                if line.trim() == "ERROR" {
                    return Err(());
                }

                if line.contains("+CCLK:") {
                    found_time = parse_cclk_line(line);
                }
            }
        })
        .await;

        if res.is_ok() { found_time } else { None }
    }

    // Helper to check CLTS status
    async fn check_clts_enabled(&mut self) -> Result<bool, ()> {
        self.send_str("AT+CLTS?").await;
        self.send_str("\r\n").await;

        let mut is_enabled = None;

        let res = with_timeout(Duration::from_millis(2000), async {
            loop {
                let line = self.read_line().await.map_err(|_| ())?;
                let trimmed = line.trim();

                if trimmed == "OK" {
                    return Ok(());
                }
                if trimmed == "ERROR" {
                    return Err(());
                }

                // Response format: +CLTS: <mode>
                if let Some(enabled) = parse_clts_query_line(line) {
                    is_enabled = Some(enabled);
                }
            }
        })
        .await;

        if res.is_ok() {
            is_enabled.ok_or(())
        } else {
            Err(())
        }
    }

    // -----------------------------------------------------------------------
    // High Level Operations
    // -----------------------------------------------------------------------

    pub async fn power_on(&mut self) {
        if self.is_powered {
            return;
        }

        info!("Starting SIM800 Power Sequence...");

        // 1. Hardware Power On
        self.control.set_dc_power(PowerState::On);
        Timer::after(Duration::from_millis(1500)).await;

        info!("Pulsing PWRKEY...");
        self.control.set_power_key(PowerState::On);
        Timer::after(Duration::from_millis(1200)).await;
        self.control.set_power_key(PowerState::Off);

        info!("Waiting for SIM800 boot...");
        Timer::after(Duration::from_secs(INIT_SIM800_DELAY_SECONDS as u64)).await;

        // 2. Handshake
        let mut attempts = 0;
        loop {
            
            if self.send_cmd_wait_ok("AT", HANDSHAKE_TIMEOUT_MS).await.is_ok() {
                break;
            }
            attempts += 1;
            if attempts > HANDSHAKE_ATTEMPTS {
                error!("AT Handshake failed after {} attempts", attempts);
                break;
            }
            Timer::after(Duration::from_millis(500)).await;
        }
        let _ = self.send_cmd_wait_ok("ATE0", DEFAULT_TIMEOUT_MS).await;

        // 3. Check and Fix Time Sync (CLTS)
        // This ensures the setting is written to ROM and the module reboots if needed.
        match self.check_clts_enabled().await {
            Ok(false) => {
                info!("CLTS disabled. Enabling, Saving and Rebooting module...");
                let _ = self.send_cmd_wait_ok("AT+CLTS=1", DEFAULT_TIMEOUT_MS).await;
                let _ = self.send_cmd_wait_ok("AT&W", DEFAULT_TIMEOUT_MS).await; // Write to ROM

                // Reset module to apply changes
                // AT+CFUN=1,1 -> Full functionality, Reset
                self.send_str("AT+CFUN=1,1\r\n").await;

                // Wait for reboot (similar to initial boot delay)
                Timer::after(Duration::from_secs(8)).await;

                // Re-handshake after reboot
                let _ = self.send_cmd_wait_ok("AT", DEFAULT_TIMEOUT_MS).await;
                let _ = self.send_cmd_wait_ok("ATE0", DEFAULT_TIMEOUT_MS).await;
                info!("Module rebooted. CLTS should be active.");
            }
            Ok(true) => {
                info!("CLTS is already enabled.");
            }
            Err(_) => {
                warn!("Failed to query CLTS status.");
            }
        }

        // 4. Standard Initialization
        let cmds = [
            "AT+CMEE=1",          // Extended Error reporting
            "AT+CLIP=1",          // Caller ID
            "AT+CMGF=1",          // SMS Text Mode
            "AT+CSCS=\"GSM\"",    // Character Set
            "AT+CNMI=1,2,0,1,0",  // New Message Indications
            "AT+CSMP=49,167,0,0", // SMS Text Mode Parameters
            "AT+CREG=1",          // Network Registration Report
            "AT+DDET=1",          // DTMF Detection
        ];

        for cmd in cmds {
            let mut attempts = 0;
            loop {
                if self.send_cmd_wait_ok(cmd, DEFAULT_TIMEOUT_MS).await.is_ok() {
                    break;
                }
                attempts += 1;
                if attempts > 3 {
                    error!("CMD failed: {}", cmd);
                    break;
                }
                Timer::after(Duration::from_millis(500)).await;
            }
        }

        // 5. Load Phonebook
        info!("Loading Phonebook...");
        for i in 1..=8 {
            let mut buf = String::<16>::new();
            use core::fmt::Write;
            let _ = write!(buf, "AT+CPBR={}", i);
            let _ = self.send_cmd_wait_ok(&buf, 2000).await;
        }

        self.is_powered = true;
        info!("SIM800 Initialized and Ready");
    }

    pub async fn power_off(&mut self) {
        if !self.is_powered {
            self.control.set_power_key(PowerState::Off);
            self.control.set_dc_power(PowerState::Off);
            return;
        }

        info!("Disabling SIM800 power supply...");
        self.control.set_power_key(PowerState::Off);
        Timer::after(Duration::from_millis(100)).await;
        self.control.set_dc_power(PowerState::Off);
        self.is_powered = false;
    }

    async fn ensure_powered(&mut self) {
        if !self.is_powered {
            self.power_on().await;
        }
    }

    async fn restore_usb_modem_mode_if_needed(&mut self) {
        #[cfg(feature = "receiver")]
        {
            self.power_on().await;
        }

        #[cfg(not(feature = "receiver"))]
        {
            if self.usb_connected {
                self.power_on().await;
            } else {
                self.power_off().await;
            }
        }
    }

    pub async fn send_sms(&mut self, number: &str, message: &str) -> Result<(), ()> {
        self.ensure_powered().await;
        self.send_str("AT+CMGS=\"").await;
        self.send_str(number).await;
        self.send_str("\"\r\n").await;

        let res = with_timeout(Duration::from_secs(5), async {
            loop {
                let mut b = [0u8; 1];
                if self.rx.read(&mut b).await.is_ok() {
                    if b[0] == b'>' {
                        return Ok::<(), ()>(());
                    }
                }
            }
        })
        .await;

        if res.is_err() {
            return Err(());
        }

        self.send_str(message).await;
        let ctrl_z = [0x1Au8];
        let _ = self.tx.write(&ctrl_z).await;

        self.send_cmd_wait_ok("", 10000).await
    }

    pub async fn make_call_dtmf(&mut self, number: &str, dtmf: &str) -> Result<(), ()> {
        self.ensure_powered().await;
        self.send_str("ATD").await;
        self.send_str(number).await;
        self.send_str(";\r\n").await;

        let result = with_timeout(Duration::from_secs(20), async {
            loop {
                let line = self.read_line().await?;
                info!("Call setup line: {}", line);
                if line_indicates_call_connected(
                    line,
                    ONLINE_SIGNAL.chars().next().unwrap_or('\0'),
                ) {
                    return Ok::<(), ()>(());
                }
                if line_indicates_call_failed(line) {
                    return Err(());
                }
            }
        })
        .await;

        if result.is_err() {
            self.send_cmd_wait_ok("AT+CHUP", DEFAULT_TIMEOUT_MS).await.ok();
            return Err(());
        }

        let mut out_buf = [0u8; 64];
        if let Some(csv) = separate_chars_by_commas(dtmf, &mut out_buf) {
            let mut cmd = String::<64>::new();
            use core::fmt::Write;
            let _ = write!(cmd, "AT+VTS=\"{}\"", csv);
            self.send_cmd_wait_ok(&cmd, 5000).await?;
        } else {
            self.send_cmd_wait_ok("AT+CHUP", DEFAULT_TIMEOUT_MS).await.ok();
            return Err(());
        }

        let confirm_res = with_timeout(Duration::from_secs(10), async {
            loop {
                let line = self.read_line().await?;
                info!("Received during confirmation wait: {}", line);
                if line_indicates_call_failed(line) {
                    return Err(());
                }
                if line_indicates_call_connected(
                    line,
                    CONFIRMATION_SIGNAL.chars().next().unwrap_or('\0'),
                ) {
                    self.send_cmd_wait_ok("AT+CHUP", DEFAULT_TIMEOUT_MS).await.ok();
                    return Ok::<(), ()>(());
                }
            }
        })
        .await;

        if confirm_res.is_err() {
            self.send_cmd_wait_ok("AT+CHUP", DEFAULT_TIMEOUT_MS).await.ok();
        }

        match confirm_res {
            Ok(_) => Ok(()),
            Err(_) => Err(()),
        }
    }

    pub async fn handle_incoming_call_flow(
        &mut self,
        event_channel: &Sender<'static, CriticalSectionRawMutex, SimEvent, 4>,
    ) {
        self.ensure_powered().await;
        self.send_cmd_wait_ok("ATA", 2000).await.ok();
        Timer::after(Duration::from_secs(1)).await;

        let mut cmd = String::<32>::new();
        use core::fmt::Write;
        let _ = write!(cmd, "AT+VTS=\"{}\"", ONLINE_SIGNAL);
        self.send_cmd_wait_ok(&cmd, 2000).await.ok();

        let mut dtmf_buf = String::<DTMF_PACKET_LENGTH>::new();

        let receive_res = with_timeout(Duration::from_secs(10), async {
            loop {
                let line = self.read_line().await?;
                info!("Incoming call flow line: {}", line);
                if let Some(c) = parse_dtmf_char(line) {
                    dtmf_buf.push(c).ok();
                    event_channel.send(SimEvent::DtmfReceived(c)).await;
                }
                if dtmf_buf.len() >= DTMF_PACKET_LENGTH {
                    return Ok::<(), ()>(());
                }
                if line.contains("NO CARRIER") {
                    return Err(());
                }
            }
        })
        .await;

        if receive_res.is_ok() {
            cmd.clear();
            let _ = write!(cmd, "AT+VTS=\"{}\"", CONFIRMATION_SIGNAL);
            self.send_cmd_wait_ok(&cmd, 2000).await.ok();
            Timer::after(Duration::from_secs(1)).await;
        }

        //self.send_cmd_wait_ok("AT+CHUP", 1000).await.ok();

        event_channel.send(SimEvent::CallEnded).await;
    }

    pub async fn run(
        &mut self,
        cmd_channel: Receiver<'static, CriticalSectionRawMutex, Command, 4>,
        event_channel: Sender<'static, CriticalSectionRawMutex, SimEvent, 4>,
    ) {
        let mut uptime_sec: u64 = 0;

        loop {
            use embassy_futures::select::{Either3, select3};

            let mut usb_rx_buf = [0u8; 64];
            let usb_fut = USB_RX_PIPE.read(&mut usb_rx_buf);
            let selection = if self.is_powered {
                select3(self.read_line(), cmd_channel.receive(), usb_fut).await
            } else {
                select3(core::future::pending(), cmd_channel.receive(), usb_fut).await
            };

            uptime_sec += 1;

            match selection {
                Either3::First(line_res) => {
                    let mut sms_sender: Option<String<MAX_PHONE_LENGTH>> = None;

                    if let Ok(line) = line_res {
                        if !line.trim().is_empty() {
                            info!("RX: {}", line);

                            if let Some(urc) = classify_urc(line) {
                                match urc {
                                    ParsedUrc::SmsHeader { number } => {
                                        sms_sender = Some(number);
                                    }
                                    ParsedUrc::Clip { number } => {
                                        event_channel
                                            .send(SimEvent::CallReceived { number })
                                            .await;
                                    }
                                    ParsedUrc::Dtmf(c) => {
                                        event_channel.send(SimEvent::DtmfReceived(c)).await;
                                    }
                                    ParsedUrc::Time(time) => {
                                    info!(
                                        "Time received (URC): {}-{}-{} {}:{}:{}",
                                        time.year,
                                        time.month,
                                        time.day,
                                        time.hour,
                                        time.minute,
                                        time.second
                                    );
                                    event_channel.send(SimEvent::TimeReceived(time)).await;
                                }
                                }
                            }
                        }
                    }

                    if let Some(sender) = sms_sender {
                        if let Ok(msg) = self.read_line().await {
                            let mut s_msg = String::new();
                            s_msg.push_str(msg).ok();
                            event_channel
                                .send(SimEvent::SmsReceived {
                                    number: sender,
                                    message: s_msg,
                                })
                                .await;
                        }
                    }
                }
                Either3::Second(cmd) => {
                    info!("Processing command: {:?}", cmd);
                    match cmd {
                        Command::Init => self.power_on().await,
                        Command::UsbConnected => {
                            self.usb_connected = true;
                            self.power_on().await;
                        }
                        Command::UsbDisconnected => {
                            self.usb_connected = false;
                            self.usb_cmd.reset();

                            #[cfg(feature = "receiver")]
                            self.power_on().await;

                            #[cfg(not(feature = "receiver"))]
                            self.power_off().await;
                        }
                        Command::SendMessage {
                            phone_number,
                            message,
                        } => {
                            let _ = self.send_sms(&phone_number, &message).await;
                            self.restore_usb_modem_mode_if_needed().await;
                        }
                        Command::SendAlarmSms { message } => {
                            if let Some(target_num) = first_phonebook_number(&self.phone_book) {
                                let _ = self.send_sms(&target_num, &message).await;
                            }
                            self.restore_usb_modem_mode_if_needed().await;
                        }
                        Command::CallAlarmWithDtmf { dtmf } => {
                            match decide_alarm_call(
                                &self.phone_book,
                                &self.alarm_dedup,
                                &dtmf,
                                uptime_sec,
                            ) {
                                AlarmCallDecision::SkipDuplicate => {
                                    warn!(
                                        "Skipping duplicate alarm call for DTMF {} (Last: {}s ago)",
                                        dtmf,
                                        uptime_sec - self.alarm_dedup.last_time
                                    );
                                    event_channel.send(SimEvent::CallExecuted(true)).await;
                                    self.restore_usb_modem_mode_if_needed().await;
                                }
                                AlarmCallDecision::PlaceCall { number } => {
                                    info!("Calling Alarm: {} with DTMF: {}", number, dtmf);
                                    match self.make_call_dtmf(&number, &dtmf).await {
                                        Ok(_) => {
                                            info!("Alarm confirmed (#).");
                                            self.alarm_dedup.record_success(&dtmf, uptime_sec);
                                            event_channel.send(SimEvent::CallExecuted(true)).await;
                                        }
                                        Err(_) => {
                                            warn!("Alarm call failed/unconfirmed.");
                                            event_channel.send(SimEvent::CallExecuted(false)).await;
                                        }
                                    }
                                    self.restore_usb_modem_mode_if_needed().await;
                                }
                                AlarmCallDecision::NoNumber => {
                                warn!("No phone number for alarm call!");
                                event_channel.send(SimEvent::CallExecuted(false)).await;
                                }
                            }
                        }
                        Command::CallWithDtmf { phone_number, dtmf } => {
                            let _ = self.make_call_dtmf(&phone_number, &dtmf).await;
                            self.restore_usb_modem_mode_if_needed().await;
                        }
                        Command::HandleIncomingCall { .. } => {
                            self.handle_incoming_call_flow(&event_channel).await;
                            self.restore_usb_modem_mode_if_needed().await;
                        }
                        Command::UpdateTime => {
                            if let Some(time) = self.execute_update_time().await {
                                info!(
                                    "Time updated (CMD): {}-{}-{} {}:{}:{}",
                                    time.year,
                                    time.month,
                                    time.day,
                                    time.hour,
                                    time.minute,
                                    time.second
                                );
                                event_channel.send(SimEvent::TimeReceived(time)).await;
                            } else {
                                warn!("Failed to parse time from +CCLK");
                            }
                            self.restore_usb_modem_mode_if_needed().await;
                        }
                    }
                }
                Either3::Third(n) => {
                    if n > 0 {
                        for i in 0..n {
                            let b = usb_rx_buf[i];
                            let outcome = self.usb_cmd.push_byte(b, self.is_powered);

                            if outcome.echo {
                                let _ = USB_TX_PIPE.try_write(&[b]);
                            }
                            if outcome.forward_to_modem {
                                let _ = self.tx.write(&[b]).await;
                            }
                            if let Some(cmd) = outcome.command_to_execute {
                                self.execute_mcu_command(cmd.as_str()).await;
                            }
                        }
                    }
                }
            }
        }
    }

    async fn execute_mcu_command(&mut self, _cmd: &str) {}
}
